### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by gllmhyt** [joar/mediagoblin-init-scripts#3]
I got this error when starting mediagoblin-celeryd service with the latest git version of MediaGoblin, which has a newer version of Celery.

``` python
Traceback (most recent call last):
  File "/var/www/mediagoblin/bin/celeryd", line 9, in <module>
    load_entry_point('celery==2.5.3', 'console_scripts', 'celeryd')()
  File "/var/www/mediagoblin/local/lib/python2.7/site-packages/celery-2.5.3-py2.7.egg/celery/bin/celeryd.py", line 201, in main
    worker.execute_from_commandline()
  File "/var/www/mediagoblin/local/lib/python2.7/site-packages/celery-2.5.3-py2.7.egg/celery/bin/base.py", line 87, in execute_from_commandline
    return self.handle_argv(prog_name, argv[1:])
  File "/var/www/mediagoblin/local/lib/python2.7/site-packages/celery-2.5.3-py2.7.egg/celery/bin/base.py", line 125, in handle_argv
    return self.run(*args, **options)
  File "/var/www/mediagoblin/local/lib/python2.7/site-packages/celery-2.5.3-py2.7.egg/celery/bin/celeryd.py", line 101, in run
    return self.app.Worker(**kwargs).run()
  File "/var/www/mediagoblin/local/lib/python2.7/site-packages/celery-2.5.3-py2.7.egg/celery/apps/worker.py", line 129, in run
    self.worker_init()
  File "/var/www/mediagoblin/local/lib/python2.7/site-packages/celery-2.5.3-py2.7.egg/celery/apps/worker.py", line 180, in worker_init
    self.loader.init_worker()
  File "/var/www/mediagoblin/local/lib/python2.7/site-packages/celery-2.5.3-py2.7.egg/celery/loaders/base.py", line 110, in init_worker
    self.on_worker_init()
  File "/var/www/mediagoblin/local/lib/python2.7/site-packages/celery-2.5.3-py2.7.egg/celery/loaders/default.py", line 85, in on_worker_init
    self.import_default_modules()
  File "/var/www/mediagoblin/local/lib/python2.7/site-packages/celery-2.5.3-py2.7.egg/celery/loaders/base.py", line 105, in import_default_modules
    for module in imports | self.builtin_modules]
  File "/var/www/mediagoblin/local/lib/python2.7/site-packages/celery-2.5.3-py2.7.egg/celery/loaders/base.py", line 92, in import_task_module
    return self.import_from_cwd(module)
  File "/var/www/mediagoblin/local/lib/python2.7/site-packages/celery-2.5.3-py2.7.egg/celery/loaders/base.py", line 100, in import_from_cwd
    package=package)
  File "/var/www/mediagoblin/local/lib/python2.7/site-packages/celery-2.5.3-py2.7.egg/celery/utils/__init__.py", line 398, in import_from_cwd
    return imp(module, package=package)
  File "/var/www/mediagoblin/local/lib/python2.7/site-packages/celery-2.5.3-py2.7.egg/celery/loaders/base.py", line 95, in import_module
    return importlib.import_module(module, package=package)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/mediagoblin/mediagoblin/processing/task.py", line 35, in <module>
    @celery.task(default_retry_delay=2 * 60)
TypeError: 'module' object is not callable
```

**Comment by joar** [comment]
Can you run celeryd via `lazyceleryd.sh`?

**Comment by gllmhyt** [comment]
I have the same error. :/ So I think it's related to recent celery changes in MediaGoblin, not your script.

**Comment by gllmhyt** [comment]
I've seen a message in the mailing list related to a problem with celery upgrade. I followed the manual upgrade of celery and it worked. Sorry for the disturbing with unrelated bug to your scripts (that work fine !).

**Comment by joar** [comment]
Good to hear it's working for you :)
